### ISSUE TITLE
BUG: KeyboardMapping breaks spoilers arming

### ISSUE THREAD

**Issue by Guy-Adler** [GeoFS-Autoland/spoilers-arming#11]
Keyboard mapping needs to be integrated into spoilers arming for it not to break.
https://github.com/GeoFS-Autoland/spoilers-arming/tree/integrate-keyboard-mapping

**Comment by nicolas377** [comment]
We might need to inject a ap++ style content/dom script pair to let spoiler arming know to run keyboard mapping.

**Comment by nicolas377** [comment]
See [here](https://github.com/GeoFS-Autoland/autoland/blob/main/source/scripts/autopilot_pp_infra/content_communicator.ts) and [here](https://github.com/GeoFS-Autoland/autoland/blob/main/source/scripts/autopilot_pp_infra/dom_communicator.ts) for examples of how ap++ uses the content/dom pair to get data from the chrome extension into the window object

**Comment by nicolas377** [comment]
@Guy-Adler could you make a draft pr for this? don't mark it ready, but it'll help out

**Comment by nicolas377** [comment]
If you need, I'll get a DOM/content script pair to get the window.keyboard_mapping object you're looking for.

**Comment by Guy-Adler** [comment]
yeah
we dont need to inject anything, we can just see if the keyboard_mapping object is present on the window.
The problem right now is that when activating the spoilers manually, the arming should be disabled, and it is not being disabled right now. the fix is probably simple

**Comment by Guy-Adler** [comment]
Will be fixed on #12
